mode = "wlf"

graph_representation = "ilg"
iterations = 2

features = "wl"
optimisation = "rank-svm"
feature_pruning = "a-m"
hash = "set"

data_pruning = "equivalent-weighted"
state_representation = "all"
