mode = "wlf"

graph_representation = "nilg"
iterations = 1

features = "ccwl"
optimisation = "rank-svm"
feature_pruning = "none"
hash = "set"

data_pruning = "none"
state_representation = "numeric-downward"
